### ISSUE TITLE
Image with a fixed height?

### ISSUE THREAD

**Issue by GertTimmerman** [spatie/statamic-responsive-images#30]
Just a question: i have a photoslider and want to have each image have the same height. But if i use the code below it does not resize the image:

```{{ responsive:image glide:height="100" }}```

I have two questions:

1. I have researched the code for an answer, but it seems you only optimize a image if a width is given and remove the height attributes of an image (Resonsive.php:159). Is that because of a reason?
2. For the photoslider, i must have the width and height attributes of the img tag set to the resized dimensions. Now the dimensions of the original image is used, is that because of a reason?

**Comment by riasvdv** [comment]
Having a fixed height on the image itself defeats the purpose of having responsive images, because that results in a fixed width as well.

The best solution to this is to set the fixed height on a wrapping element, and have the image scale based on that width a max height, since responsive images are based on the width they're displayed at in the `sizes` attribute.

If you're not able to solve it this way, I'd suggest just using Statamic's Glide tag instead for your slider.
