### ISSUE TITLE
Images not generated or displayed

### ISSUE THREAD

**Issue by jmartsch** [spatie/statamic-responsive-images#50]
I updated from v1.8.0 to v2.4.4 and now my images don't display anymore.
I used a normal image field as the source and used this code:
```
{{ teaser_image }}
        {{ responsive:url glide:height="400" ratio="16/9" alt="{title}" class="w-full" placeholder="false"}}
        {{ /teaser_image }}
```
The result is an empty picture Element:
```
<picture>
        <source srcset="">
    <img alt="5 Tipps damit Ihre Website neue Kunden bringt" class="w-full" width="2365" height="1330.3125">
</picture>
```
This code worked before.

I even tried the simplest form `{{ responsive:teaser_image }}` but the output is the same.

Then I tried using the new responsive fieldtype,
![image](https://user-images.githubusercontent.com/551551/107776220-941a8580-6d41-11eb-8ea0-54314c8d0c34.png)

with this tag: `{{ responsive:teaser_responsive }}` but still to no avail. The output looks like this:
```
<picture>
        <source srcset="">
    <img width="2365" height="1774">
</picture>
```

**Comment by jeffwhitfield** [comment]
Yeah, I'm having a similar problem. However, in my case, the problem is that the images generated with the `responsive:generate` command aren't being used at all. This is with v2.4.4. 

I tested this by observing the generated images for a page that had just one image. 16 images were generated for this image by the `responsive:generate` command. After attempting to load the page, more images were generated and I ended up with 33 images in that same directory. Plus, the page errored with a 500 internal server error. Something is askew! Gonna roll back the versions to see if I can find the culprit.

**Comment by jeffwhitfield** [comment]
Ok, so I did some testing. I went back as far as v2.0.0 and the problem still existed. When I switched to v1.8.0 the problem went away. Only one extra image was created, which was a very small thumbnail (presumably for the control panel). All other images remained the same and the front-end used the images created by `responsive:generate`. So, yeah, something in v2.x was introduced that invalidates the images created by `responsive:generate` thus forcing the recreation of cached images. Not good. :(

**Comment by riasvdv** [comment]
@jeffwhitfield You're describing a different issue, please make a separate issue for that.

@jmartsch Are your images working when you use normal `glide` tags?

**Comment by jeffwhitfield** [comment]
@riasvdv Deleted my comments and created a new ticket. :)

**Comment by riasvdv** [comment]
v2.5.0 released which should solve this

**Comment by jmartsch** [comment]
Yes. Problem seems fixed. Thank you.
